/// StudyNote.swift
/// Data models for study output, including the @Generable type
/// used by Apple's FoundationModels framework.

import Foundation
import FoundationModels

// MARK: - Structured output from the on-device model

/// The two sections generated by Apple Foundation Models (phase 1).
/// Phase 2 will add historical background and cross-reference explanations
/// via a local LLM and the TSK dataset.
@Generable
struct PassageAnalysis {
    @Guide(description: "2-3 sentences describing the narrative context: who wrote this, to whom, and what is happening in this specific passage within the broader story of the book")
    var context: String

    @Guide(description: "Exactly 3 practical applications of this passage for a modern reader. Each application should be 1-2 sentences and directly grounded in the text.")
    var applications: [String]
}

// MARK: - UI data model

/// The assembled study note shown in the UI.
struct StudyNote: Identifiable {
    let id = UUID()
    let reference: BibleReference
    /// Full ESV text — present only when the passage is ≤5 verses.
    let verseText: String?
    let context: String
    let applications: [String]
    let createdAt: Date = .now
}
